# Generated by Django 3.2.6 on 2024-02-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_family_guests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guests',
            new_name='Guest',
        ),
    ]
