# Generated by Django 3.2.6 on 2024-02-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_guest_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dietary_restrictions',
            field=models.TextField(blank=True),
        ),
    ]
